### ISSUE TITLE
How to start the optimization from a custom initial pulse instead of LIN/ZERO/RND? 

### ISSUE THREAD

**Issue by jishnurajendran** [ajgpitch/qtrl-tutorial#3]
_init_pulse_type_ argument in the _qutip.control.pulseoptim.optimize_pulse_ 
Is it possible to define a custom initail pulse type?

**Comment by ajgpitch** [comment]
I believe you should see an example of how to do this in:
qtrl-tutorial/ctrl_pulse_optim-example-QFT-init_amps_file.py

Hope that helps.

Alex
